name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: leodotsinc/.github/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      app_dir: leodots.dev
      service_name: blog
      container_name: leodots-blog
